husband(captain_mark_phillips, princess_anne).
wife(queen_elizabethII, prince_phillip).
sibling(peter_phillips, zara_phillips).
mother(X, prince_andrew).
niece(princess_charlotte, princess_anne).
aunt(princess_diana, princess_charlotte).
grandson(X, prince_charles).
grandchild(X, princess_diana).
uncle(prince_harry, princess_eugenie).
grandchild(X, queen_elizabethII).
wife(X, prince_charles).
husband(X, princess_anne).
sister(X, james_viscount_severn).
daughter(X, princess_anne).
son(X, sarah_ferguson).
daughter(X, sarah_ferguson).
grandparent(princess_diana, prince_harry).
brother(prince_george, princess_charlotte).
uncle(timothy_laurence, james_viscount_severn).
grandmother(X, princess_charlotte).