laDienThoai(X).
laDienThoai(p40pro).
laDienThoai(gt2e).
laDienThoaiPhoThong(X).
laDienThoaiPhoThong(nova21).
laDienThoaiPhoThong(p40).
sanpham(mateSeries,X).
sanpham(pSeries,X).
sanpham(novaSeries,X).
sanpham(gSeries,X).
sanpham(ySeries,X).
laDongHo(X).
laDongHo(gt2e).
laDongHo(fbpro).
laPhuKienUaChuong(X).
laPhuKienUaChuong(flpro).
laPhuKienUaChuong(fbstudio).
laTaiNghe(X).
laTaiNghe(fbstudio).
laPhanMem(X).
